### ISSUE TITLE
Space image cache is wrong

### ISSUE THREAD

**Issue by ChaituVR** [stamp-labs/stamp#119]
In some cases, even if we pass new `cb` param, the image stored in cache is old avatar

Example https://cdn.stamp.fyi/space/wen🌕.eth?s=96&cb=c178562f8f12066b here is this case `c178562f8f12066b` belong to new image hash but somehow in cache we still have old image

i may delete the cache soon so for future reference:

when i visit link above, I see this 
![image](https://github.com/snapshot-labs/stamp/assets/15967809/9b9e905c-6a2c-428e-8930-46a59ff33465)

if i change `cb` to something else it works 
![image](https://github.com/snapshot-labs/stamp/assets/15967809/86098820-4ddc-41e8-93da-ed079d740ebc)

On UI `cb` is generated with `const hash = sha256(props.space.avatar).slice(0, 16);` 
while `props.space.avatar` value is `ipfs://bafybeiatkvzda3w6xquzv2dkn5gn7f3jrfarxh6bwy5t3lid2hut5qooie`

**Comment by Sekhmet** [comment]
Do we have some more recent example of broken cache? The one in the task no longer works.

**Comment by wa0x6e** [comment]
I’ve never been able to reproduce the issue. 

My take on solving this was to refactor the code, to extract the cache engine

**Comment by Sekhmet** [comment]
We had bug that could cause it, but it should have been solved before this issue was created so I'm not sure: https://github.com/stamp-labs/stamp/pull/55

Ideally we should have repro so we can see if what we do actually fixes it, without it I don't think I'd bother.

**Comment by Sekhmet** [comment]
We can reopen if we reproduce it.
