### ISSUE TITLE
Add URL param to set fallback resolver

### ISSUE THREAD

**Issue by bonustrack** [stamp-labs/stamp#280]
We should add an URL param for the avatar and token endpoint to define which fallback resolver should be used if there isn't any image available from resolvers. I imagine the param to be ?fb=blockies or ?fb=jazzicon. This should work with the cache system, in a way that it doesn't conflict with others app using different fallback resolver.

**Comment by wa0x6e** [comment]
avatara fallback already exist

**Comment by bonustrack** [comment]
Ok missed that, closing this issue
